"""CSV intake and deterministic data-quality gate."""

from pathlib import Path

import pandas as pd
import streamlit as st

from src.data_intake.validator import DerivationConfig, deidentify_patient_ids, validate_population_dataset
from src.i18n import is_zh
from src.models import BreastROIInputs


ZH_COPY = {
    "Upload, validate, and approve a patient-level CSV before model evaluation or outreach prioritization.": "在模型评估或外展优先级排序前，上传、校验并批准患者级 CSV。",
    "Uploaded files stay in the current app session. This MVP does not write patient-level uploads to a database.": "上传文件仅保留在当前应用会话中；此 MVP 不会将患者级数据写入数据库。",
    "1. Select a dataset": "1. 选择数据集", "Data source": "数据来源", "Upload CSV": "上传 CSV",
    "Built-in synthetic test file": "内置合成测试数据", "Choose a CSV file": "选择 CSV 文件",
    "Use the standard schema shown in the downloadable template. Maximum recommended demo size: 100,000 rows.": "请使用下载模板中的标准字段；演示版本建议最多 100,000 行。",
    "The bundled 10,000-row synthetic dataset is ready for validation.": "内置的 10,000 行合成数据已准备好进行校验。",
    "The CSV could not be read. Check its encoding, delimiter, and column structure.": "无法读取 CSV，请检查编码、分隔符及字段结构。",
    "Standard input schema": "标准输入字段", "Unique patient identifier": "唯一患者标识", "Evaluation label": "评估真值标签",
    "Field": "字段", "Type": "类型", "Requirement": "要求", "Download standard synthetic CSV": "下载标准合成 CSV",
    "The file exceeds the 100,000-row MVP limit.": "文件超过 MVP 的 100,000 行限制。",
    "2. Data quality gate": "3. 数据质量门禁", "Rows": "行数", "Columns": "列数",
    "Failed checks": "失败检查", "Warnings": "警告", "Dataset type": "数据集类型",
    "Synthetic": "合成数据", "Uploaded / unverified": "上传数据 / 未验证", "Check": "检查项",
    "Status": "状态", "Details": "详情", "Affected rows": "受影响行数", "Preview normalized data": "预览标准化数据",
    "3. Human approval": "5. 应用数据集", "All blocking quality checks passed. Review the dataset before approval.": "所有阻断性质量检查均已通过，可以将该数据集用于下游分析。",
    "Approval note": "批准说明", "Explain the purpose and limitations of this dataset.": "说明该数据集的用途与局限性。",
    "Approve for evaluation and prioritization": "应用于评估与优先级仿真",
    "An approval note is required for the audit trail.": "审计记录要求填写批准说明。",
    "Dataset approved. It is now available for downstream analysis and outreach prioritization.": "数据集已应用，现在可用于外展资源优化及后续决策分析。",
    "Approval is blocked until all failed checks are resolved.": "存在失败检查，修复前无法批准。",
    "Currently approved session dataset": "当前会话已批准数据", "Source": "来源", "De-identified": "已去标识化",
    "Not required — synthetic": "无需处理——合成数据", "Remove approved session dataset": "移除当前会话数据",
    "Yes": "是", "PASS": "通过", "FAIL": "失败", "WARN": "警告",
    "Required columns": "必要字段", "Patient IDs": "患者 ID", "Duplicate IDs": "重复患者 ID",
    "Missing or invalid values": "缺失或无效值", "Age range": "年龄范围",
    "Screening history range": "筛查历史范围", "Probability ranges": "概率范围",
    "Synthetic marker": "合成数据标识", "Sample size": "样本量",
    "All required columns are present.": "所有必要字段均已提供。",
    "All rows have a patient ID.": "每一行均包含患者 ID。", "Patient IDs are unique.": "患者 ID 均不重复。",
    "Core fields are complete and parseable.": "核心字段完整且可正确解析。",
    "All ages are within 40–74.": "所有年龄均在 40–74 岁范围内。",
    "Screening history values are in range.": "筛查历史数值均在允许范围内。",
    "All probability fields are between 0 and 1.": "所有概率字段均在 0–1 之间。",
    "Every row is explicitly marked synthetic.": "每一行均已明确标记为合成数据。",
    "Dataset contains at least 100 records.": "数据集至少包含 100 条记录。",
    "Hospital input fields": "医院原始字段", "All hospital input fields are present.": "医院原始必填字段均已提供。",
    "As-of date": "数据基准日", "All as-of dates are valid.": "所有数据基准日均有效。",
    "Last screen date": "最近筛查日期", "Prior-screened patients have a valid last_screen_date.": "有既往筛查的患者均提供了有效的最近筛查日期。",
    "Date chronology": "日期先后关系", "Screening dates follow valid chronology.": "筛查日期先后关系有效。",
    "Required status fields": "必要状态字段", "Required status fields are parseable.": "必要状态字段均可正确解析。",
    "Derivation settings": "派生规则设置", "Screening interval (years)": "筛查间隔（年）",
    "Base completion assumption (%)": "基础筛查完成率假设（%）", "System-derived fields": "系统派生字段",
    "These fields are generated by the platform and are not required from the hospital.": "以下字段由平台生成，不要求医院上传。",
    "Derived field": "派生字段", "Source type": "来源类型", "Formula / source": "公式或来源",
    "System-derived preview": "系统派生结果预览", "Care Gap rule": "Care Gap 规则",
    "Transparent rule score": "透明规则评分", "Demo assumption": "演示假设", "R-model parameter": "R 模型参数",
}


def tt(text: str) -> str:
    """Page-local copy keeps Chinese working even during Streamlit hot reload."""
    return ZH_COPY.get(text, text) if is_zh() else text

SAMPLE_PATH = Path(__file__).parents[1] / "data" / "test_datasets" / "synthetic_hospital_breast_screening_raw_v2.csv"

st.caption(tt("Upload, validate, and approve a patient-level CSV before model evaluation or outreach prioritization."))
st.info(
    tt("Uploaded files stay in the current app session. This MVP does not write patient-level uploads to a database."),
    icon=":material/privacy_tip:",
)

with st.container(border=True):
    st.subheader(tt("1. Select a dataset"))
    source = st.segmented_control(
        tt("Data source"), [tt("Upload CSV"), tt("Built-in synthetic test file")],
        default=tt("Upload CSV"), key="intake_source",
    )
    uploaded = None
    if source == tt("Upload CSV"):
        uploaded = st.file_uploader(tt("Choose a CSV file"), type=["csv"], accept_multiple_files=False)
        st.caption(tt("Use the standard schema shown in the downloadable template. Maximum recommended demo size: 100,000 rows."))
    else:
        st.success(tt("The bundled 10,000-row synthetic dataset is ready for validation."), icon=":material/dataset:")

raw = None
source_name = None
try:
    if uploaded is not None:
        raw = pd.read_csv(uploaded)
        source_name = uploaded.name
    elif source == tt("Built-in synthetic test file"):
        raw = pd.read_csv(SAMPLE_PATH)
        source_name = SAMPLE_PATH.name
except (UnicodeDecodeError, pd.errors.ParserError, ValueError) as error:
    st.error(tt("The CSV could not be read. Check its encoding, delimiter, and column structure."))
    st.code(str(error))

if raw is None:
    st.subheader(tt("Standard input schema"))
    schema = pd.DataFrame(
        [
            ["患者ID（patient_id）", "文本", tt("Unique patient identifier")],
            ["数据基准日（as_of_date）", "日期", "YYYY-MM-DD"],
            ["年龄（age）", "整数", "40–74 岁"],
            ["最近筛查日期（last_screen_date）", "日期", "从未筛查者可留空"],
            ["从未筛查（never_screened）", "布尔值", "是 / 否（true / false）"],
            ["已有预约（has_active_appointment）", "布尔值", "是 / 否（true / false）"],
            ["允许外展（outreach_consent）", "布尔值", "是 / 否（true / false）"],
            ["既往异常（prior_abnormal）", "布尔值", "选填"],
            ["家族史（family_history）", "布尔值", "选填"],
            ["首选语言（preferred_language）", "文本", "选填"],
            ["所属诊所（clinic_id）", "文本", "选填"],
        ],
        columns=[tt("Field"), tt("Type"), tt("Requirement")],
    )
    st.dataframe(schema, hide_index=True, width="stretch")
    st.download_button(
        tt("Download standard synthetic CSV"), SAMPLE_PATH.read_bytes(), SAMPLE_PATH.name,
        "text/csv", icon=":material/download:",
    )
    st.stop()

if len(raw) > 100_000:
    st.error(tt("The file exceeds the 100,000-row MVP limit."))
    st.stop()

st.subheader("2. 系统派生规则")
st.caption(tt("These fields are generated by the platform and are not required from the hospital."))
with st.container(border=True):
    st.markdown(f"**{tt('Derivation settings')}**")
    setting_columns = st.columns(2)
    screening_interval = setting_columns[0].number_input(tt("Screening interval (years)"), 0.5, 10.0, 2.0, 0.5)
    completion_assumption = setting_columns[1].slider(tt("Base completion assumption (%)"), 0, 100, 45)

roi_values = st.session_state.get("roi_inputs_snapshot", vars(BreastROIInputs()))
roi_inputs = BreastROIInputs(**roi_values)
normalized, report = validate_population_dataset(
    raw,
    DerivationConfig(
        screening_interval_years=float(screening_interval),
        base_completion_probability=float(completion_assumption) / 100,
        roi_inputs=roi_inputs,
    ),
)
st.subheader(tt("2. Data quality gate"))
with st.container(horizontal=True):
    st.metric(tt("Rows"), f"{report.row_count:,}", border=True)
    st.metric(tt("Columns"), report.column_count, border=True)
    st.metric(tt("Failed checks"), report.failure_count, border=True)
    st.metric(tt("Warnings"), report.warning_count, border=True)
    st.metric(tt("Dataset type"), tt("Synthetic") if report.is_synthetic else tt("Uploaded / unverified"), border=True)

check_table = pd.DataFrame(
    [{tt("Check"): tt(check.name), tt("Status"): tt(check.status), tt("Details"): tt(check.detail), tt("Affected rows"): check.affected_rows} for check in report.checks]
)
st.dataframe(
    check_table, hide_index=True, width="stretch",
    column_config={tt("Affected rows"): st.column_config.NumberColumn(format="%d")},
)

with st.expander(tt("Preview normalized data"), icon=":material/preview:"):
    st.dataframe(normalized.head(100), hide_index=True, width="stretch")

if report.passed and report.input_schema == "hospital_raw":
    st.subheader(f"4. {tt('System-derived fields')}")
    lineage = pd.DataFrame(
        [
            ["years_since_screen", "距上次筛查年数", tt("Care Gap rule"), "（数据基准日 − 最近筛查日期）÷ 365.25；从未筛查设为 20 年"],
            ["ground_truth_gap", "Care Gap 标签", tt("Care Gap rule"), f"从未筛查或距上次筛查 ≥ {screening_interval:g} 年；已有预约或不同意外展则排除"],
            ["care_gap_score", "Care Gap 分数", tt("Transparent rule score"), "筛查逾期程度、从未筛查、既往异常、家族史加权；预约及不同意外展扣分"],
            ["completion_probability", "完成筛查概率", tt("Demo assumption"), f"基础假设 {completion_assumption}% ，根据已上传行为/风险字段做透明调整"],
            ["detection_probability", "癌症检出概率", tt("R-model parameter"), f"R 参数 {roi_inputs.cancer_detection_per_1000:g}/1,000 × 年龄段发病率校正系数"],
        ],
        columns=[tt("Derived field"), "中文名称", tt("Source type"), tt("Formula / source")],
    )
    st.dataframe(lineage, hide_index=True, width="stretch")
    with st.expander(tt("System-derived preview"), icon=":material/function:"):
        st.dataframe(
            normalized[["patient_id", "years_since_screen", "ground_truth_gap", "care_gap_score", "completion_probability", "detection_probability"]].head(100),
            hide_index=True, width="stretch",
        )

st.subheader(tt("3. Human approval"))
if report.passed:
    st.success(tt("All blocking quality checks passed. Review the dataset before approval."), icon=":material/check_circle:")
    if st.button(tt("Approve for evaluation and prioritization"), type="primary", icon=":material/verified_user:"):
        approved = normalized.copy() if report.is_synthetic else deidentify_patient_ids(normalized)
        st.session_state["approved_population"] = approved
        st.session_state["approved_population_metadata"] = {
            "source_name": source_name,
            "row_count": len(approved),
            "is_synthetic": report.is_synthetic,
            "approval_note": "Quality gate passed; applied by user.",
            "deidentified": not report.is_synthetic,
        }
        # A newly approved hospital dataset must invalidate any older demo
        # scenario so the assistant cannot mix 100,000-person sample inputs
        # with the newly uploaded population.
        for key in (
            "assistant_scenario", "assistant_result", "assistant_report",
            "assistant_roi_inputs_snapshot",
            "assistant_parameter_sources", "assistant_detection_value",
            "assistant_recall_value", "assistant_dataset_signature",
        ):
            st.session_state.pop(key, None)
        st.success(tt("Dataset approved. It is now available for downstream analysis and outreach prioritization."))
else:
    st.error(tt("Approval is blocked until all failed checks are resolved."), icon=":material/block:")

current = st.session_state.get("approved_population_metadata")
if current:
    with st.container(border=True):
        st.subheader(tt("Currently approved session dataset"))
        st.write(f"**{tt('Source')}:** {current['source_name']}")
        st.write(f"**{tt('Rows')}:** {current['row_count']:,}")
        st.write(f"**{tt('De-identified')}:** {tt('Yes') if current['deidentified'] else tt('Not required — synthetic')}")
        if st.button(tt("Remove approved session dataset"), icon=":material/delete:"):
            st.session_state.pop("approved_population", None)
            st.session_state.pop("approved_population_metadata", None)
            st.rerun()
